#!/bin/bash
# this script give the number of files in subdirectories.
# If the list of directories is not specified as arguments
# (wildcards allowed), all the subdir are taken into consideration
# class = @File management tools@

usage() {
    echo
    echo "USAGE: $(basename $0) [-h] [-s] [list of directories]"
    echo
    echo "  PURPOSE:"
    echo "     Count the number of inodes in all the directories below the actual"
    echo "     working directory. (All the sub directory tree is take into account.)"
    echo "     This tool is very usefull to analyse places in your tree where there"
    echo "     are too many files :) that may cause quota overflow."
    echo
    echo "  OPTIONS:"
    echo "     -h : print this message "
    echo "     -s : add the size of the directories"
    echo "     list_of_directories: restrict the inodes counting to the directories"
    echo "                          in the list."
    echo
    exit 0
        }

psz=0  # print size flag

while getopts :hs  opt
  do
    case $opt in 
       (h)  usage ;;
       (s)  psz=1 ;;
       (*) ;;
    esac
  done

shift $(($OPTIND-1))

dirs="*"

if [ $# != 0 ] ; then dirs="$*" ; fi

for f in $dirs ; do
  if [ -d $f ] ;  then
#  nf=$( \ls -lR $f | grep -vi total | grep -vi ':$' | grep -vi '^$' | wc -l )
#  nf=$( find $f -type f  | wc -l )
  nf=$( find $f \( -type f -o -type l \)  | wc -l )
  s=''
  if [ $psz = 1 ] ; then
   s="( $( du -sh $f | awk '{ print $1}' ) )"
  fi
  echo $nf " " $s $f
  fi
done
