#!/bin/bash
# this script give the number of files in subdirectories.
# If the list of directories is not specified as arguments
# (wildcards allowed), all the subdir are taken into consideration

#------------------------------------------------------------
#  $Rev: 353 $
#  $Date: 2011-12-07 21:57:43 +0100 (Wed, 07 Dec 2011) $
#  $Id: inode.bash 353 2011-12-07 20:57:43Z molines $
#--------------------------------------------------------------

usage() {
    echo
    echo "USAGE: $(basename $0) [-h] [list of directories]"
    echo
    echo "  PURPOSE:"
    echo "     Count the number of inodes in all the directories below the actual"
    echo "     working directory. (All the sub directory tree is take into account.)"
    echo "     This tool is very usefull to analyse places in your tree where there"
    echo "     are too many files :) that may cause quota overflow."
    echo
    echo "  OPTIONS:"
    echo "     -h : print this message "
    echo "     list_of_directories: restrict the inodes counting to the directories"
    echo "                          in the list."
    echo
    exit 0
        }

while getopts :h  opt
  do
    case $opt in 
       (h)  usage ;;
       (*) ;;
    esac
  done

shift $(($OPTIND-1))

dirs="*"

if [ $# != 0 ] ; then dirs="$*" ; fi

for f in $dirs ; do
  if [ -d $f ] ;  then
#  nf=$( \ls -lR $f | grep -vi total | grep -vi ':$' | grep -vi '^$' | wc -l )
#  nf=$( find $f -type f  | wc -l )
  nf=$( find $f \( -type f -o -type l \)  | wc -l )
  echo $nf " " $f
  fi
done
