#!/bin/bash
# Create xml code ( XIOS 1) for including new domains in domain_def.xml
# class = @XIOS browse tools@

usage() {
   echo
   echo "USAGE: $(basename $0 ) -d DOM [-c coordinates_file] [ -h ] xmin xmax ymin ymax"
   echo
   echo "  PURPOSE:"
   echo "     Print the xml lines do be inserted in domain_ref.xml file in order to create "
   echo "     a new domain for XIOS output."
   echo "     This version is for XIOS1 : deprecated and obsolete"
   echo "     New version to be written for XIOS2 "
   echo
   echo "  ARGUMENTS:"
   echo "     -d DOM : indicate a domain name for the xml file."
   echo "     xmin xmax ymin ymax : position of the domain in geographical coordinates."
   echo "                This 4 variable MUST be the last on the line."
   echo
   echo "  OPTIONS:"
   echo "     -h : Display this help message."
   echo "     -c coordinates_file: Use this coordinate file instead of default $coord."
   echo
   exit 0
        }

coord=coordinates.nc
while getopts :hc:d: opt; do
   case $opt in
     (h) usage ;;
     (c) coord=${OPTARG} ;;
     (d) dom=${OPTARG} ;;
  esac
done

shift $((OPTIND - 1 ))

xmin=$1 ; shift
xmax=$1 ; shift
ymin=$1 ; shift
ymax=$1 ; shift

 tmp=$(cdffindij $xmin $xmax $ymin $ymax -c $coord -p T  | tail -2 | head -1 )
 imin=$( echo $tmp | awk '{print $1}' )
 imax=$( echo $tmp | awk '{print $2}' )
 jmin=$( echo $tmp | awk '{print $3}' )
 jmax=$( echo $tmp | awk '{print $4}' )
 ni=$(( imax - imin + 1 ))
 nj=$(( jmax - jmin + 1 ))

echo '<domain id="'$dom'T" zoom_ibegin="'$imin'" zoom_jbegin="'$jmin'" zoom_ni="'$ni'" zoom_nj="'$nj'"  /> '
echo '<domain id="'$dom'U" zoom_ibegin="'$imin'" zoom_jbegin="'$jmin'" zoom_ni="'$ni'" zoom_nj="'$nj'"  /> '
echo '<domain id="'$dom'V" zoom_ibegin="'$imin'" zoom_jbegin="'$jmin'" zoom_ni="'$ni'" zoom_nj="'$nj'"  /> '
echo '<domain id="'$dom'W" zoom_ibegin="'$imin'" zoom_jbegin="'$jmin'" zoom_ni="'$ni'" zoom_nj="'$nj'"  /> '
