#!/bin/bash
#------------------------------------------------------------
#  $Rev: 353 $
#  $Date: 2011-12-07 21:57:43 +0100 (Wed, 07 Dec 2011) $
#  $Id: dcmtk_elapsed.bash 353 2011-12-07 20:57:43Z molines $
#--------------------------------------------------------------
#set -x
#
difftime() { d2=$( echo $1 | awk '{print $3 *86400}')  ;  h2=$( echo $1 | awk '{print  $4}' | awk -F: '{ print $1*3600 + $2*50 + $3 }') ;
             d1=$( echo $2 | awk '{print $3 *86400}')  ;  h1=$( echo $2 | awk '{print  $4}' | awk -F: '{ print $1*3600 + $2*50 + $3 }') ;
             dt=$( echo 1 | awk '{print d2 - d1 + h2 -h1 }' d2=$d2 d1=$d1 h2=$h2 h1=$h1 ) ;  echo $dt ;}

LookInNamelist()    { eval grep -e $1 namelist.${CONFCASE}     | sed -e 's/=/  = /' | awk ' {if ( $1 == str ) print $3 }' str=$1 ; }

if [ $# = 0 ] ; then 
   echo " USAGE:  $(basename $0) nemo_logfile.o "
   echo "    Will scan the job outputfile and use the timing information to infer a prognostic"
   echo "    about the elapsed time required for 1 year of run."
   echo "    This command must be used in CTL where both logfiles and namelists are."
   exit 0
fi

logfile=$1

CONFCASE=$( echo $( basename $(dirname $PWD ) ) )

start=$(grep -A 2 -e 'Run the code' $logfile  | tail -1)
stpstart=$(grep -A 3 -e 'Run the code' $logfile  | tail -1 | awk '{ print $1}' )

ends=$(cat $logfile | grep -v report | grep -B 1 -e 'Post processing'  | tail -2 | head -1 ) 
stpend=$(cat $logfile | grep -v report | grep -B 2 -e 'Post processing' | tail -3 | head -1 | awk '{ print $1}') 


echo $start
echo $stpstart
echo $ends
echo $stpend
#exit
nstep=$(( $stpend - $stpstart + 1 ))

elapsed=$(difftime "$ends" "$start" )
echo This run did  $nstep steps  in $elapsed seconds
rdt=$( LookInNamelist rn_rdt ) 
nstep_day=$(echo $rdt | awk '{ print 86400/$1}' )

step_year=$( echo $nstep_day | awk '{ print $1*365}' )

echo $step_year

yearelapsed=$( echo $elapsed $step_year $nstep | awk '{ print $1/$3*$2/3600}' )

echo One year elapsed is estimated to $yearelapsed  hours.
