#!/bin/bash
# This script is used to perform an update of file from /scratch to /data
# if some files are removed from scratch
# It is a wrapper to ddcp and scan all the years in a directory

#------------------------------------------------------------
#  $Rev: 17 $
#  $Date: 2010-11-10 11:02:14 +0100 (Wed, 10 Nov 2010) $
#  $Id: mcpdd 17 2010-11-10 10:02:14Z molines $
#--------------------------------------------------------------
usage() {
   echo
   echo "USAGE: $(basename $0) [-h] "
   echo
   echo "  PURPOSE:"
   echo "     Perform a mirroring of all the subdirectories of the current directory"
   echo "     on SDIR. This script must be used in the CONFCASE-S or CONFCASE-MEAN "
   echo "     directory. All subdirectories are visited and files copied to SDIR/CONFIG/..."
   echo
   echo "  ARGUMENTS:"
   echo "     No arguments for this script."
   echo
   echo "  OPTIONS:"
   echo "     -h : Display this help page "
   echo
   exit 0
        }

while getopts :h opt ; do
   case $opt in 
     (h) usage ;;
     (*) usage ;;
   esac
done

if [ ! $SDIR ] ; then
   echo ERROR: Environment variable SDIR must be set before using $(basename $0)
   echo
   usage
fi

here=$(pwd)
here=$(basename $here)

CONFIG=${here%%-*}
CONFCASE=${here%-*}
dirtype=${here##*-}

CASE=${CONFCASE#*-}

if [ $dirtype != 'S' -o $dirtype != 'MEAN' ] ; then 
   echo ERROR: You are not in a CONFCASE-S or CONFCASE-MEAN directory
   echo
   usage
fi


for d in * ; do
if [ -d $d ] ; then
  cd $d
   WDIR=$SDIR/$CONFIG/$here/$d
   dcmtk_cpdd
  cd ../
fi
done

